name: CI

env:
  PACKAGE: ssi
  PYTHON: 3.6

on:
  pull_request:
  push:
    paths:
    - '**.py'

jobs:
  test:
    name: flake8 and pytest notebooks
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install -e .

    - name: Lint with flake8
      run: |
        pip install flake8
        flake8 setup.py $PACKAGE/

    - name: Test notebooks
      run: |
        pip install pytest nbval
        pytest --nbval-lax notebooks/Photometric_fit.ipynb

  pypi:
    name: Deploy to PyPI
    if: contains(github.ref, 'refs/tags/')
    needs: [test]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine

    - name: Build package
      run: python setup.py sdist bdist_wheel

    - name: Publish to PyPI
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      run: twine upload $PYPI_REPO dist/*
